---
- name: Common Configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
  - three_tier_common
  tasks:
  - include_role:
      name: three_tier_frontend
    when: >-
      'frontends' in group_names
  - include_role:
      name: three_tier_app
    when: >-
      'apps' in group_names
  - include_role:
      name: three_tier_appdb
    when: >-
      'appdbs' in group_names
